name: Build DinryX APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/kivy/buildozer:latest

    steps:
      - uses: actions/checkout@v4

      - name: Fix pip & install Cython
        run: |
          python3 -m pip install pip==24.3.1
          python3 -m pip install Cython==0.29.36

      - name: Clean Buildozer cache
        run: |
          rm -rf .buildozer

      - name: Accept Android SDK licenses
        run: |
          yes | sdkmanager --licenses || true

      - name: Build APK
        run: |
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DinryX-Mobile-APK
          path: bin/*.apk
